name: 'Terraform Deploy'
description: 'Initialize, plan, and apply Terraform configuration'
branding:
  icon: 'cloud'
  color: 'purple'

inputs:
  terraform-version:
    description: 'Terraform version to use'
    required: false
    default: '1.5.0'
  working-directory:
    description: 'Working directory for Terraform'
    required: false
    default: 'infra/terraform'
  terraform-wrapper:
    description: 'Enable Terraform wrapper'
    required: false
    default: 'true'
  format-check:
    description: 'Run terraform fmt -check'
    required: false
    default: 'true'
  auto-approve:
    description: 'Auto-approve Terraform apply'
    required: false
    default: 'true'
  environment:
    description: 'Environment name (dev, staging, prod)'
    required: false
    default: 'dev'

outputs:
  plan-exitcode:
    description: 'Terraform plan exit code'
    value: ${{ steps.plan.outputs.exitcode }}

runs:
  using: 'composite'
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform-version }}
        terraform_wrapper: ${{ inputs.terraform-wrapper }}
    
    - name: Terraform Format Check
      if: inputs.format-check == 'true'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: terraform fmt -check
      continue-on-error: true
    
    - name: Terraform Init
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: terraform init
    
    - name: Terraform Validate
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: terraform validate
    
    - name: Terraform Plan
      id: plan
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: terraform plan -out=tfplan
    
    - name: Terraform Apply
      if: inputs.auto-approve == 'true'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: terraform apply -auto-approve tfplan
